[tool.commitizen]
bump_message = "release $current_version â†’ $new_version []"
update_changelog_on_bump = true
changelog_incremental = true
changelog_start_rev = "v0.4.7"
gpg_sign = true
allow_abort = true
