site_name: Hitchhiker's Guide
site_author: Anonymous Planet
site_description: "The comprehensive guide for online anonymity and OpSec."
site_dir: '/site/'
docs_dir: 'docs/'
site_url: "https://www.anonymousplanet.org/"
repo_url: "https://github.com/Anon-Planet/thgtoa"
repo_name: ""
#edit_uri: ""
theme:
  name: material
  favicon: media/profile.png
  icon:
    logo: material/bird
    repo: simple/github
  font:
    text: Public Sans
    code: Liberation Mono
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
      primary: green
      accent: blue
    - scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
      primary: grey
      accent: teal

plugins:
  - social: {}
#  - with-pdf:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#  - macros: {}
#  - meta: {}
#  - git-latest-tag: {}
# - git-authors: {}
#  - git-latest-release: {}

extra:
  social:
    - icon: simple/mastodon
      link: https://mastodon.social/@anonymousplanet
      name: Mastodon
    - icon: simple/gitlab
      link: http://wmj5kiic7b6kjplpbvwadnht2nh2qnkbnqtcv3dyvpqtz7ssbssftxid.onion/
      name: "0xacab"
    - icon: simple/gitea
      link: http://it7otdanqu7ktntxzm427cba6i53w6wlanlh23v5i3siqmos47pzhvyd.onion/anonymousplanetorg
      name: Darktea
    - icon: simple/github
      link: https://github.com/anon-planet
      name: Github
    - icon: simple/gitlab
      link: https://gitlab.com/anonymousplanetorg
      name: Gitlab
    - icon: simple/codeberg
      link: https://codeberg.org/anonymousplanet
      name: Codeberg
    # - icon: simple/torbrowser
    #   link: http://thgtoa3jzy3doku7hkna32htpghjijefscwvh4dyjgfydbbjkeiohgid.onion/
    #   name: Hidden service

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.critic: {}
  - pymdownx.caret: {}
  - pymdownx.keys: {}
  - pymdownx.mark: {}
  - pymdownx.tilde: {}
  - pymdownx.snippets: {}
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list: {}
  - def_list: {}
  - md_in_html: {}
  - meta: {}
  - abbr: {}
  - tables: {}
  - footnotes: {}
  - toc:
      permalink: true
      toc_depth: 3

copyright: |
  &copy; 2023-2025 <a href="https://anonymousplanet.org/"  target="_blank" rel="noopener">Anonymous Planet</a>
